### PR TITLE
Merge master

### PR DESCRIPTION
**Pull request by ericmj**

### CODE REVIEW

**Comment by ericmj** [comment]
It's okay if the history isn't clean when we finally merge this into hex_web. This is such a big change and has diverged from master so much it's not worth working on rebasing it. If I do the rebase @pragmaticivan will also lose his contributions so I think this is the best solution.

**Comment by wojtekmach** [comment]
@ericmj 

> It's okay if the history isn't clean when we finally merge this into hex_web. This is such a big change and has diverged from master so much it's not worth working on rebasing it. If I do the rebase @pragmaticivan will also lose his contributions so I think this is the best solution.

before the redesign PR lands on hex_web:master I can definitely take a stab (for 1-2h) at rebasing the PR and keeping all @pragmaticivan commits in there (the sha would change obviously) as well as tests passing at all times. I think this would be really helpful later to read history but more importantly to e.g. run `git bisect` etc. If I fail after 1h or 2h we could merge it in anyway. WDYT?

**Comment by ericmj** [comment]
That would be great. Please go ahead.

On Saturday, 2 April 2016, Wojtek Mach notifications@github.com wrote:

> @ericmj https://github.com/ericmj
> 
> It's okay if the history isn't clean when we finally merge this into
> hex_web. This is such a big change and has diverged from master so much
> it's not worth working on rebasing it. If I do the rebase @pragmaticivan
> https://github.com/pragmaticivan will also lose his contributions so I
> think this is the best solution.
> 
> before the redesign PR lands on hex_web:master I can definitely take a
> stab (for 1-2h) at rebasing the PR and keeping all @pragmaticivan
> https://github.com/pragmaticivan commits in there (the sha would change
> obviously) as well as tests passing at all times. I think this would be
> really helpful later to read history but more importantly to e.g. run git
> bisect etc. If I fail after 1h or 2h we could merge it in anyway. WDYT?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/pragmaticivan/hex_web/pull/1#issuecomment-204649399

## 

Eric Meadows-Jönsson

**Comment by wojtekmach** [comment]
@ericmj @pragmaticivan sorry for a late reply, hope you haven't been waiting for me :)

I was able to rebase this branch with master and I think it looks good - tests are passing and the site looks reasonable well _on each commit_. I can't guarantee that I haven't introduced any regressions, but after the rebase the diff was almost identical (except 1 line in JS) with Eric's branch.

Here's the branch rebased with latest master: https://github.com/wojtekmach/hex_web/commits/wm-frontend-rebased. Feel free to use this branch and let me know if I can help in the meantime.

**Comment by ericmj** [comment]
@wojtekmach Thanks for the work. I'll be closing this since the rebase has better history.

**Pull request closed without merging**
